runtime: php55
api_version: 1
threadsafe: true
includes:
  - creds.yaml
handlers:

- url: /test/
  script: backend/test.php
- url: /static/generic.png
  static_files: frontend/loveeu/static/generic.png
  upload: frontend/loveeu/static/generic.png
- url: /static/generic-heymp.png
  static_files: frontend/loveeu/static/generic-heymp.png
  upload: frontend/loveeu/static/generic-heymp.png
- url: /favicon.ico
  script: backend/favicon.php
- url: /
  script: backend/home.php
- url: /hey/.*
  script: backend/heymp.php
- url: /heyimg/.*
  script: backend/image-heymp.php
- url: /images/.*
  script: backend/image-loveeu.php
- url: /.*
  script: backend/loveeu.php